/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidor;
import interfaz.implementacioninterfaceRmi;
import java.awt.Color;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class Servidor extends javax.swing.JFrame {
Registry rg;
    /**
     * Creates new form Servidor
     */
    public Servidor() {
        try {
           initComponents(); 
           rg = LocateRegistry.createRegistry(5000);
           btn_detener.setEnabled(false);
            setResizable(false);
            
        } catch (RemoteException ex) {
            Logger.getLogger(Servidor.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    public void iniciar(){
        try {
            rg.rebind("Calculadora", new implementacioninterfaceRmi());
            btn_iniciar.setEnabled(false);
            btn_detener.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Servidor iniciado.....");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void detener(){
        try {
            rg.unbind("Calculadora");
            btn_iniciar.setEnabled(true);
            btn_detener.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Servidor detenido.....");
            
        } catch (RemoteException e) {
            System.out.println(e.getMessage());
        }catch(NotBoundException ex){
            System.out.println(ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_iniciar = new javax.swing.JButton();
        btn_detener = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("SERVIDOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, -1));

        btn_iniciar.setText("INICIAR SERVIDOR");
        btn_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_iniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_iniciarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_iniciarMousePressed(evt);
            }
        });
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        btn_detener.setText("DETENER SERVIDOR");
        btn_detener.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_detenerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_detenerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_detenerMousePressed(evt);
            }
        });
        btn_detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detenerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_detener, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        // TODO add your handling code here:
        iniciar();
    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void btn_iniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciarMouseEntered
        // TODO add your handling code here:
        btn_iniciar.setBackground(new Color(59,79,255));
    }//GEN-LAST:event_btn_iniciarMouseEntered

    private void btn_iniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciarMouseExited
        // TODO add your handling code here:
                btn_iniciar.setBackground(new Color(59,79,123));

    }//GEN-LAST:event_btn_iniciarMouseExited

    private void btn_iniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciarMousePressed
        // TODO add your handling code here:
                btn_iniciar.setBackground(new Color(59,79,123));

    }//GEN-LAST:event_btn_iniciarMousePressed

    private void btn_detenerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_detenerMouseEntered
        // TODO add your handling code here:
        btn_detener.setBackground(new Color(59,79,255));

    }//GEN-LAST:event_btn_detenerMouseEntered

    private void btn_detenerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_detenerMouseExited
        // TODO add your handling code here:
        btn_detener.setBackground(new Color(59,79,123));

    }//GEN-LAST:event_btn_detenerMouseExited

    private void btn_detenerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_detenerMousePressed
        // TODO add your handling code here:
        btn_detener.setBackground(new Color(59,79,123));

    }//GEN-LAST:event_btn_detenerMousePressed

    private void btn_detenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detenerActionPerformed
        // TODO add your handling code here:
        detener();
    }//GEN-LAST:event_btn_detenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_detener;
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
